/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciosupermercado;

import javax.swing.JOptionPane;

/**
 *
 * @author Raven
 */
public class GestionDeProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionDeProductos
     */
    public GestionDeProductos() {
        initComponents();
       cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtcodigo = new javax.swing.JTextField();
        jbbuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtdescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtprecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcrubro = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtstock = new javax.swing.JTextField();
        jbnuevo = new javax.swing.JButton();
        jbguardar = new javax.swing.JButton();
        jbeliminar = new javax.swing.JButton();
        jbsalir = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 255));
        jLabel1.setText("Gestion de Productos");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 153, 255));
        jLabel2.setText("Código");

        jtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcodigoActionPerformed(evt);
            }
        });

        jbbuscar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbbuscar.setForeground(new java.awt.Color(255, 102, 255));
        jbbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciosupermercado/icono.png"))); // NOI18N
        jbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 153, 255));
        jLabel3.setText("Descripción");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 153, 255));
        jLabel4.setText("Precio");

        jtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtprecioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 153, 255));
        jLabel5.setText("Rubro");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 153, 255));
        jLabel6.setText("Stock");

        jbnuevo.setText("Nuevo");
        jbnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnuevoActionPerformed(evt);
            }
        });

        jbguardar.setText("Guardar");
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });

        jbeliminar.setText("Eliminar");
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });

        jbsalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbsalir.setForeground(new java.awt.Color(204, 153, 255));
        jbsalir.setText("Salir");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jcrubro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jbnuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbeliminar)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbsalir)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jbbuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcrubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnuevo)
                    .addComponent(jbguardar)
                    .addComponent(jbeliminar))
                .addGap(18, 18, 18)
                .addComponent(jbsalir)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcodigoActionPerformed

    private void jtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtprecioActionPerformed

    private void jbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarActionPerformed
        // TODO add your handling code here:
        int prodS = Integer.parseInt(jtcodigo.getText());

        try {
            boolean encontrado = false;
            for (Producto prod : Menu.listaProductos) {
                if (prod.getCodigo() == prodS) {
                    jtdescripcion.setText(prod.getDescripcion());
                    jtprecio.setText(String.valueOf(prod.getPrecio()));
                    jtstock.setText(String.valueOf(prod.getStock()));
                    encontrado = true;
                    break;
                }
            }
            if (!encontrado) {
                JOptionPane.showMessageDialog(this, "Producto no encontrado");

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Solo se admiten números");
        }

     //Yadhi
     
//     try {
//    int prodS = Integer.parseInt(jtcodigo.getText());
//    Producto pro = null;
//    
//    do {
//        for (Producto prod : Menu.listaProductos) {
//            if (prod.getCodigo() == prodS) {
//                pro = prod; 
//                jtdescripcion.setText(prod.getDescripcion());
//                jtprecio.setText(prod.getPrecio() + "");
//                jtstock.setText(prod.getStock() + "");
//            }
//        }
//        
//        if (pro == null) {
//            JOptionPane.showMessageDialog(this, "Producto no encontrado");
//            break; 
//        }
//    } while (pro.getCodigo() != prodS);
//    
//} catch (NumberFormatException e) {
//    JOptionPane.showMessageDialog(this, "Solo se admiten números");
//}


    }//GEN-LAST:event_jbbuscarActionPerformed

    private void jbnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnuevoActionPerformed
        // TODO add your handling code here:
       
        jtdescripcion.setText("");
        jtprecio.setText("");
        jtstock.setText("");

    }//GEN-LAST:event_jbnuevoActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed
        // TODO add your handling code here:
        int prodS = Integer.parseInt(jtcodigo.getText());

        try {

            for (Producto prod : Menu.listaProductos) {
                borrarFilas();

                if (prod.getCodigo() == prodS) {

                    Categoria rubro;
                    if (jcrubro.getModel().getSelectedItem() == "COMESTIBLE") {
                        rubro = Categoria.COMESTIBLE;
                    } else if (jcrubro.getModel().getSelectedItem() == "LIMPIEZA") {
                        rubro = Categoria.LIMPIEZA;
                    } else {
                        rubro = Categoria.PERFUMERIA;
                    }

                    int codigo = Integer.parseInt(jtcodigo.getText());
                    String descripcion = jtdescripcion.getText();
                    double precio = Double.parseDouble(jtprecio.getText());
                    int stock = Integer.parseInt(jtstock.getText());

                    Menu.listaProductos.remove(new Producto(codigo, descripcion, precio, stock, rubro));
                    JOptionPane.showMessageDialog(this, "Producto eliminado exitosamente");

                }

            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Solo se Admiten números");

        }


    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed
        // TODO add your handling code here:
        
          try {

            if (!jtdescripcion.getText().isEmpty() && !jtprecio.getText().isEmpty() && !jtstock.getText().isEmpty()) {
                //borrarFilas();

                Categoria rubro;
                if (jcrubro.getModel().getSelectedItem() == "COMESTIBLE") {
                    rubro = Categoria.COMESTIBLE;
                } else if (jcrubro.getModel().getSelectedItem() == "LIMPIEZA") {
                    rubro = Categoria.LIMPIEZA;
                } else {
                    rubro = Categoria.PERFUMERIA;
                }

                int codigo = Integer.parseInt(jtcodigo.getText());
                String descripcion = jtdescripcion.getText();
                double precio = Double.parseDouble(jtprecio.getText());
                int stock = Integer.parseInt(jtstock.getText());

                Menu.listaProductos.add(new Producto(codigo, descripcion, precio, stock, rubro));
                JOptionPane.showMessageDialog(this, "Producto agregado exitosamente");

            } else {
                JOptionPane.showMessageDialog(this, "No puede dejar campos vacios");
            }

        } catch (NullPointerException e) {

        }
        
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
        // TODO add your handling code here:
        
        int respuesta= JOptionPane.showConfirmDialog(this, "Estás seguro que quieres salir?","Cerrar Ventana", JOptionPane.YES_NO_OPTION);
        
        if(respuesta==JOptionPane.YES_OPTION){
            
            this.dispose();//cierro la ventana
        }
        
        
    }//GEN-LAST:event_jbsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbnuevo;
    private javax.swing.JButton jbsalir;
    private javax.swing.JComboBox<Categoria> jcrubro;
    private javax.swing.JTextField jtcodigo;
    private javax.swing.JTextField jtdescripcion;
    private javax.swing.JTextField jtprecio;
    private javax.swing.JTextField jtstock;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        jcrubro.addItem(Categoria.COMESTIBLE);
        jcrubro.addItem(Categoria.PERFUMERIA);
        jcrubro.addItem(Categoria.LIMPIEZA);
    }

    private void borrarFilas() {

        jtdescripcion.setText("");
        jtprecio.setText("");
        jtstock.setText("");

    }
    
   
}
