/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciosupermercado;

import java.util.TreeSet;

/**
 *
 * @author Raven
 */
public class Menu extends javax.swing.JFrame {
    
    public static TreeSet<Producto> listaProductos=new TreeSet<>();
    
   

    static Object listaProductos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmporprecio = new javax.swing.JMenu();
        jmporrubro = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmnombre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supermercado De Todo!");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setForeground(new java.awt.Color(153, 102, 255));
        jMenu1.setText("Administracion");

        jMenuItem1.setText("Gestion de Productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jmporprecio.setForeground(new java.awt.Color(153, 102, 255));
        jmporprecio.setText("Consultas");

        jmporrubro.setText("Por rubro");
        jmporrubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmporrubroActionPerformed(evt);
            }
        });
        jmporprecio.add(jmporrubro);

        jMenuItem3.setText("Por nombre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmporprecio.add(jMenuItem3);

        jmnombre.setText("Por precio");
        jmnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnombreActionPerformed(evt);
            }
        });
        jmporprecio.add(jmnombre);

        jMenuBar1.add(jmporprecio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();
        escritorio.repaint();
        PorNombre bpn=new PorNombre ();
        bpn.setVisible(true);
        escritorio.add(bpn);
        escritorio.moveToFront(bpn);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmporrubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmporrubroActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();
        escritorio.repaint();
        
        PorRubro porrubro=new PorRubro();
        porrubro.setVisible(true);
        escritorio.add(porrubro);
        escritorio.moveToFront(porrubro);
        
    }//GEN-LAST:event_jmporrubroActionPerformed

    private void jmnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnombreActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();
        escritorio.repaint();
        PorPrecio pp=new PorPrecio();
        pp.setVisible(true);
        escritorio.add(pp);
        escritorio.moveToFront(pp);
        
    }//GEN-LAST:event_jmnombreActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        GestionDeProductos gp=new GestionDeProductos();
        gp.setVisible(true);
        escritorio.add(gp);
        escritorio.moveToFront(gp);
        
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    public void cargarProductos(){
        listaProductos.add(new Producto(15,"Azucar x 1kg",180.75,20,Categoria.COMESTIBLE));
        listaProductos.add(new Producto(148,"Yerba x 500grs",400.45,10,Categoria.COMESTIBLE));
        listaProductos.add(new Producto(45,"Aceite 1l", 600.45,5,Categoria.COMESTIBLE));
        listaProductos.add(new Producto(23,"Shampoo 1l",725.15,12,Categoria.PERFUMERIA));
        listaProductos.add(new Producto(789,"Acondicionador",450.0,10,Categoria.PERFUMERIA));
        listaProductos.add(new Producto(238,"Jabon de Tocador x 3", 350.0,11,Categoria.PERFUMERIA));
        listaProductos.add(new Producto(465,"Lavandina 1l", 335.0,15,Categoria.LIMPIEZA));
        listaProductos.add(new Producto(456,"Detergente 500grs",250.75,40,Categoria.LIMPIEZA));
        listaProductos.add(new Producto(254,"Rejilla 1 paño",75.45,20,Categoria.LIMPIEZA));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jmnombre;
    private javax.swing.JMenu jmporprecio;
    private javax.swing.JMenuItem jmporrubro;
    // End of variables declaration//GEN-END:variables
}
